### ISSUE TITLE
Need push access to the repo or help uploading some new notebooks

### ISSUE THREAD

**Issue by msochka** [pmservice/ai-openscale-tutorials#12]
There are four notebooks that need to be pushed to the repo. They are the Model Risk Management notebooks that can be used as part of the tutorials. Who can help me with this?

The files are attached to the next comment.

**Comment by msochka** [comment]
[MRM beta notebooks.zip](https://github.com/pmservice/ai-openscale-tutorials/files/4258589/MRM.beta.notebooks.zip)

**Comment by msochka** [comment]
@kmacdonald06 @LukaszCmielowski @Maksymilian-Erazmus1 

Can one of you add these to the repo and also, possibly, give me write access? Thanks.

**Comment by LukaszCmielowski** [comment]
Mike,
 
 
I have added you write access. Cheers.
 
 

----------Pozdrawiam/Best Regards,Lukasz Cmielowski, PhD
Software architect / Data scientist | Watson OpenScale
Master inventor
IBM SWG Lab, Cracow, PolandIBM Polska Sp. z o.o. oddzial w Krakowieul. Armii Krajowej 18, 30 -150 Krakowtel. 48-12-628-9479NIP: 526-030-07-24Sad Rejonowy dla m.st. Warszawy,XIII Wydzial Gospodarczy KRS 0000012941Kapital zakladowy: 33.000.000 PLN
 
 
----- Original message -----From: Mike Sochka <notifications@github.com>To: pmservice/ai-openscale-tutorials <ai-openscale-tutorials@noreply.github.com>Cc: "Łukasz Ćmielowski" <Lukasz.Cmielowski@pl.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [pmservice/ai-openscale-tutorials] Need push access to the repo or help uploading some new notebooks (#12)Date: Thu, Feb 27, 2020 3:06 AM 
@kmacdonald06 @LukaszCmielowski @Maksymilian-Erazmus1
Can one of you add these to the repo and also, possibly, give me write access? Thanks.

**Comment by LukaszCmielowski** [comment]
@msochka I have added you write access.

**Comment by msochka** [comment]
Thanks!
