### ISSUE TITLE
PYTHON_FLASK should be FLASK_APP

### ISSUE THREAD

**Issue by scottdangelo** [pmservice/ai-openscale-tutorials#2]
Using [these instructions](https://github.com/pmservice/ai-openscale-tutorials/tree/master/applications/custom-ml-engine-bluemix#deployment-and-run-on-local-environment) I get an error:
```
 $ export PYTHON_FLASK=app.py

[master:?][scott@mac2018:~/gitRepos/Sandbox/ai-openscale-tutorials/applications/custom-ml-engine-bluemix]
 $ python -m flask run
Usage: python -m flask run [OPTIONS]

Error: Could not locate Flask application. You did not provide the FLASK_APP environment variable.
```
I believe it should be:
```
export FLASK_APP=app.py
```

**Comment by Maksymilian-Erazmus1** [comment]
Here is the commit that fixed this issue:
https://github.com/pmservice/ai-openscale-tutorials/commit/0f4743126a9d9633e5875bff9d8869bb811f5661
